# Generated by Django 5.2.16 on 2026-08-03 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Enfants de cet utilisateur (pour le rôle de Parent)', related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('MODERATOR', 'Moderator')], default='STUDENT', help_text="Rôle de l'utilisateur dans le système", max_length=20),
        ),
    ]
