# Generated by Django 5.2.16 on 2026-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_permission_role_user_deleted_at_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Biographie'),
        ),
    ]
