# Generated by Django 5.2.16 on 2026-08-01 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'course')},
        ),
    ]
