# Generated by Django 5.2.16 on 2026-08-03 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_progress_created_at_alter_progress_student'),
        ('courses', '0004_alter_lesson_options_course_status_course_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='StudentProgress',
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Progression étudiante', 'verbose_name_plural': 'Progressions étudiantes'},
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Leçon terminée ?')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Date de complétion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.lesson', verbose_name='Leçon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'verbose_name_plural': 'Progressions leçons',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
